# Generated by Django 5.1.7 on 2025-04-01 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stars', '0004_star_photo_alter_star_birth_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='title',
            field=models.CharField(max_length=100, verbose_name='Название категории'),
        ),
        migrations.AlterField(
            model_name='country',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Название страны'),
        ),
    ]
